# Generated by Django 4.2.4 on 2023-09-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Latest', 'Latest'), ('Technology', 'Technology'), ('Health', 'Health'), ('Business', 'Business'), ('Science', 'Science'), ('Sports', 'Sports')], max_length=20)),
                ('image', models.ImageField(upload_to='articles/images')),
                ('rating', models.CharField(choices=[('0', '0'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=10)),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Latest', 'Latest'), ('Technology', 'Technology'), ('Health', 'Health'), ('Business', 'Business'), ('Science', 'Science'), ('Sports', 'Sports')], max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images')),
            ],
        ),
    ]
