# Generated by Django 4.2.4 on 2023-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Sports', 'Sports'), ('Business', 'Business'), ('Science', 'Science'), ('Latest', 'Latest'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('4', '4'), ('2', '2'), ('0', '0')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(choices=[('Health', 'Health'), ('Sports', 'Sports'), ('Business', 'Business'), ('Science', 'Science'), ('Latest', 'Latest'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment')], max_length=20),
        ),
    ]
