# Generated by Django 4.2.4 on 2023-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Science', 'Science'), ('Business', 'Business'), ('Health', 'Health'), ('Latest', 'Latest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('4', '4'), ('0', '0'), ('2', '2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Science', 'Science'), ('Business', 'Business'), ('Health', 'Health'), ('Latest', 'Latest')], max_length=20),
        ),
    ]
